<main>
    <section class ="destinos">
    <?php   
        if (empty($destinos)) {
            echo "<p>No hay destinos para mostrar en esta categoría.</p>";
        } else {
            echo '<div class="destinations-grid">';
            foreach ($destinos as $destino) {
                echo '<div class="destination-card">';
                echo "<img src='{$destino->imagen_url}' alt='{$destino->nombre}'>";
                echo "<h3>{$destino->nombre}</h3>";
                echo "<p>{$destino->descripcion}</p>";
                echo '</div>';
            }
            echo '</div>';
        }
    ?>
</div>
</section>
</main>