<div class="login-container">
    <h2>Iniciar Sesión</h2>
    <form action="verify" method="POST" class="login-form">
        <div class="form-group">
            <label for="email">Email</label>
            <input id="email" type="text" name="email" required>
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input id="password" type="password" name="password" required>
        </div>
        
        <?php 
            if (isset($error)) {
                echo "<p class='error'>{$error}</p>";
            } 
        ?>

        <button type="submit">Ingresar</button>
    </form>

</div>
